name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天凌晨自动更新一次
  workflow_dispatch: # 允许手动触发更新
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # 对应的配置项，可以参考文档开启更多插件（如语言统计、成就等）
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_sections: most-used
